name: CI

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      TEST_MODE: "1"
      PYTHONUNBUFFERED: "1"
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install
        run: make install
      - name: Smoke
        run: timeout 240 make smoke
      - name: Handoff update
        run: make handoff-update
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: handoff-artifacts
          path: |
            handoff/**
            runs/**
            logs/**

  e2e:
    needs: smoke
    runs-on: ubuntu-latest
    env:
      TEST_MODE: "1"
      PYTHONUNBUFFERED: "1"
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install
        run: make install
      - name: E2E
        run: timeout 480 make e2e
      - name: Handoff update
        run: make handoff-update
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: handoff-artifacts
          path: |
            handoff/**
            runs/**
            logs/**
